# Generated by Django 4.0.1 on 2022-01-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('pontos_ganhos', models.IntegerField()),
                ('pontos_perdidos', models.IntegerField()),
                ('creat_at', models.DateTimeField()),
            ],
        ),
    ]
