# Generated by Django 4.0.1 on 2022-01-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='creat_at',
            field=models.DateField(),
        ),
    ]
