# Generated by Django 4.0.1 on 2022-01-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_insert_creat_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insert',
            old_name='creat_at',
            new_name='created_at',
        ),
    ]
