# Generated by Django 4.0.1 on 2022-01-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_creat_at_insert_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insert',
            name='created_at',
        ),
    ]
