# Generated by Django 4.0.1 on 2022-01-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_insert_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
