# Generated by Django 4.0.1 on 2022-01-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_insert_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insert',
            old_name='empresa',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='insert',
            old_name='pontos_ganhos',
            new_name='earned_points',
        ),
        migrations.RenameField(
            model_name='insert',
            old_name='pontos_perdidos',
            new_name='spent_points',
        ),
    ]
